herokuapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register_form/', views.register_form, name='register_form')
]

home/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username_text = models.CharField(db_column='Username', max_length=50)
    first_name_text = models.CharField(db_column='FirstName', max_length=50)
    last_name_text = models.CharField(db_column='LastName', max_length=50)
    join_date = models.DateTimeField(db_column='date joined')
    def __str__(self):
        return self.username_text + ' (' + self.first_name_text + ' ' + self.last_name_text + ')'

class AccountType(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_type_text = models.CharField(db_column='AccountType', max_length=50)
    def __str__(self):
        return self.account_type_text

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import User

def index(request):
    users = User.objects.all()
    context = { 'users': users }
    return render(request, 'home/index.html', context)

def register(request):
    return render(request, 'home/register.html')

def login(request):
    return HttpResponse("You are at the login page")

def register_form(request):
    return_message = { 'error_message': "Please fill in all required fields." }
    return render(request, 'home/register.html', return_message)

home/templates/home/index.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!doctype html>
<html lang="en">
    <head>
        <title>Home</title>
    </head>
    <body>
        <div class="col-md-12" align="center">
            <br/>
            <h1 style="color: green">HOMEPAGE<h1>
            <p>This is your homepage</p><br/>
            {% if users %}
                <h1>Currently registered users</h3>
                <ul class="text-left" style="display:inline-block;">
                {% for user in users %}
                    <li style="font-size:30px;">{{user}}</li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No users are registered.</p>
            {% endif %}
        </div>
        </br>
        <div class="col-md-12" align="center">
            <a href="{% url 'home:register' %}" class="btn btn-success btn-lg col-md-3" role="button">Register here</a>
        </div>
    </body>
</html>

home/templates/home/register.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!doctype html>
<html lang="en">
    <head>
        <title>Register</title>
    </head>
    <body>
        <div class="col-md-12" style="margin-top:1%;">
            <a href="{% url 'home:index' %}" class="btn btn-info col-md-1" role="button">Back</a>
        </div>
        <div class="col-md-12" align="center">
            <h1 style="color: green">Register<h1>
            <p>Fill out the forms</p>
        </div>
        <form class="col-md-12" align="center" action="{% url 'home:register_form' %}" method="post">
            {% csrf_token %}
            <div class="form-group" align="center">
                <label for="inputlg">Username</label>
                <input class="form-control form-control-lg col-md-2" id="username-input" type="text"
                    action="{% url 'home:register_form' %}" method="post">
            </div>
            <div class="form-group" align="center">
                <label for="inputlg">First Name</label>
                <input class="form-control form-control-lg col-md-2" id="first-name-input" type="text"
                    action="{% url 'home:register_form' %}" method="post">
            </div>
            <div class="form-group" align="center">
                <label for="inputlg">Last Name</label>
                <input class="form-control form-control-lg col-md-2" id="last-name-input" type="text"
                    action="{% url 'home:register_form' %}" method="post">
            </div>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <input type="submit" value="Vote" class="btn btn-success btn-lg col-md-3" role="button">
        </form>
        </br>
    </body>
</html>